name: test.x64

on:
  release:
    types: published
  watch:
      types: started

env:
  REPO_URL: https://github.com/Lienol/openwrt
  REPO_BRANCH: dev-19.07
  SSH_ACTIONS: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization Environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
        sudo -E apt-get -y purge azure-cli hhvm firefox powershell ghc* zulu* llvm* google* dotnet* openjdk* mysql* php*
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex node-uglify gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx-ucl libelf-dev autoconf automake libtool autopoint device-tree-compiler libuv-dev
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean

    - name: Clone Source Code
      run: |
        chmod +x ./src.sh && ./src.sh
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt

    - name: Update Install Feed
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Load Custom Configuration
      run: |
        chmod +x ./customize.sh
        cd openwrt && ../customize.sh

    - name: SSH Connection to Actions
      uses: csexton/debugger-action@master
      if: env.SSH_ACTIONS == 'true'

    - name: Download Package
      run: |
        cd openwrt
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Multi-thread Compile
      run: |
        echo -e "$(nproc) thread compile"
        cd openwrt && make -j$(nproc) V=s

    - name: Send Mail
      uses: dawidd6/action-send-mail@master
      with:
        server_address: smtp.163.com
        server_port: 465
        username: ${{secrets.send_email_user}}
        password: ${{secrets.send_email_password}}
        subject:  ${{github.workflow}} 编译完成
        body: ${{github.workflow}} 编译完成.
        to: ${{secrets.to_email}}
        from: GitHub Actions

    - name: Assemble Artifact
      uses: actions/upload-artifact@master
      with:
        name: ${{github.workflow}}
        path: openwrt/bin